version: "3.9"
services:
  webapi-norexia-gc:
    image: norexia.azurecr.io/norexia-gestioncommerciale-webapi:latest
    environment:
        ASPNETCORE_ENVIRONMENT: Test
    ports:
      - "5001:80"
    links:
      - "db:database"
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
